// <auto-generated />
namespace CreditCommitee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2018112901 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2018112901));
        
        string IMigrationMetadata.Id
        {
            get { return "201811291925108_20181129-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
