// <auto-generated />
namespace CreditCommitee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _2018120302 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2018120302));
        
        string IMigrationMetadata.Id
        {
            get { return "201812031148254_20181203-02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
